---
- hosts: all
  become: yes
  handlers:
          - name: restart httpd
            service:
                    name: httpd
                    state: restarted

  tasks:
          - name: install httpd
            yum:
                    name: httpd
                    state: present
            notify:
                    - restart httpd
