---
- hosts: all
  become: true
  tasks:
          - name: install httpd web server
            yum:
                    name: httpd
                    state: present
                    update_cache: yes

          - name: start httpd service
            service:
                    name: httpd
                    state: restarted
          - name: copy index.html file into /var/www/html
            copy:
                    src: /home/ansible/index.html
                    dest: /var/www/html/
