---
- hosts: all
  become: true
  tasks:
          - name: installing java
            yum:
                    name: java
                    state: present
            when: ansible_facts['os_family'] == "RedHat"
